#!/bin/bash
set -e

# S3 Object Storage - Docker Entrypoint
# Auto-configures the application on first run

echo "🚀 S3 Object Storage - Starting..."

# Create required directories and ensure correct permissions
echo "🔧 Configuring file permissions..."
mkdir -p /var/www/html/storage /var/www/html/logs /var/www/html/uploads
chown -R www-data:www-data /var/www/html
chmod -R 755 /var/www/html

# Suppress Apache FQDN warning
if ! grep -q "ServerName" /etc/apache2/apache2.conf; then
    echo "ServerName localhost" >> /etc/apache2/apache2.conf
fi

# Check if AUTO_INIT is enabled
if [ "$AUTO_INIT" = "true" ]; then
    echo "📦 Auto-init enabled, checking configuration..."
    
    # Wait for MySQL to be ready (extra safety)
    if [ -n "$DB_HOST" ]; then
        echo "⏳ Waiting for MySQL at $DB_HOST..."
        for i in $(seq 1 30); do
            if mysqladmin ping -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" --silent 2>/dev/null; then
                echo "✅ MySQL is ready!"
                break
            fi
            echo "   Waiting... ($i/30)"
            sleep 2
        done
    fi
    
    # Generate config.php if it doesn't exist
    CONFIG_FILE="/var/www/html/config.php"
    if [ ! -f "$CONFIG_FILE" ]; then
        echo "📝 Generating config.php..."
        
        SALT=$(openssl rand -hex 32)
        
        cat > "$CONFIG_FILE" << EOFCONFIG
<?php
/**
 * S3 Object Storage Configuration
 * Auto-generated by Docker entrypoint
 * Generated: $(date '+%Y-%m-%d %H:%M:%S')
 */

// Database Configuration (from environment)
define('DB_HOST', '${DB_HOST:-localhost}');
define('DB_NAME', '${DB_NAME:-s3_storage}');
define('DB_USER', '${DB_USER:-root}');
define('DB_PASS', '${DB_PASS:-}');
define('DB_PORT', ${DB_PORT:-3306});

// Security
define('SECRET_SALT', '${SALT}');
define('DEBUG_MODE', false);

// Paths
define('BASE_PATH', __DIR__ . '/');
define('STORAGE_PATH', BASE_PATH . 'storage/');
define('LOGS_PATH', BASE_PATH . 'logs/');
define('UPLOADS_PATH', BASE_PATH . 'uploads/');
define('MAX_FILE_SIZE', 5368709120); // 5GB

// Session Settings
define('SESSION_TIMEOUT', 7200);

// S3 API Settings
define('S3_DEFAULT_REGION', 'us-east-1');
define('S3_PERMISSIVE_AUTH', false);
define('S3_SIMPLE_AUTH', true);

// Rate Limiting
define('RATE_LIMIT_ENABLED', true);
define('RATE_LIMIT_REQUESTS', 1000);
define('RATE_LIMIT_WINDOW', 3600);

// Security
define('MAX_LOGIN_ATTEMPTS', 5);
define('LOGIN_LOCKOUT_TIME', 900);
define('SCAN_UPLOADS', true);

// Timezone
date_default_timezone_set('UTC');

// Production settings
error_reporting(0);
ini_set('display_errors', '0');
ini_set('log_errors', '1');
ini_set('error_log', LOGS_PATH . 'php_errors.log');

// Session security
if (php_sapi_name() !== 'cli' && session_status() === PHP_SESSION_NONE) {
    ini_set('session.cookie_httponly', 1);
    ini_set('session.use_strict_mode', 1);
    ini_set('session.cookie_samesite', 'Strict');
    session_start();
}

// Create directories
foreach ([STORAGE_PATH, LOGS_PATH, UPLOADS_PATH] as \$dir) {
    if (!is_dir(\$dir)) @mkdir(\$dir, 0755, true);
}
EOFCONFIG
        
        chown www-data:www-data "$CONFIG_FILE"
        chmod 640 "$CONFIG_FILE"
        echo "✅ config.php created!"
    fi
    
    # Mark as installed
    INSTALLED_FILE="/var/www/html/.installed"
    if [ ! -f "$INSTALLED_FILE" ]; then
        echo "$(date -Iseconds)" > "$INSTALLED_FILE"
        chown www-data:www-data "$INSTALLED_FILE"
        echo "✅ Installation marked complete!"
    fi
fi

echo "🎉 S3 Object Storage ready!"
echo "   📡 API: http://localhost:8080/"
echo "   🔐 Admin: http://localhost:8080/admin/"
echo "   🔑 Default: admin / admin123"
echo ""

# Run the main command
exec "$@"
